# Configuration principale du bot DOFUS
# =====================================
# Version: 1.0.0
# Créé le: 2025-08-31
# Description: Configuration centralisée pour tous les modules du bot

# Configuration de base
app:
  name: "DOFUS Bot System"
  version: "1.0.0"
  debug: false
  log_level: "INFO"  # DEBUG, INFO, WARNING, ERROR, CRITICAL
  max_threads: 4
  update_check: true

# Configuration de la base de données
database:
  type: "sqlite"
  path: "data/databases/dofus_bot.db"
  backup_path: "data/backups/"
  backup_interval: 3600  # en secondes (1 heure)
  max_backups: 24
  auto_vacuum: true
  pragma:
    journal_mode: "WAL"
    synchronous: "NORMAL"
    cache_size: -64000  # 64MB en KB
    temp_store: "MEMORY"
    mmap_size: 268435456  # 256MB

# Configuration des logs
logging:
  level: "INFO"
  format: "[%(asctime)s] %(levelname)s - %(name)s: %(message)s"
  date_format: "%Y-%m-%d %H:%M:%S"
  file_logging: true
  log_directory: "logs/"
  max_file_size: "10MB"
  backup_count: 5
  rotation_type: "time"  # time ou size
  rotation_when: "midnight"
  modules:
    core: "INFO"
    combat: "INFO"
    navigation: "INFO"
    professions: "INFO"
    economy: "INFO"
    vision: "INFO"
    safety: "WARNING"
    automation: "INFO"

# Configuration sécurité et détection
security:
  enabled: true
  anti_detection:
    human_behavior: true
    random_delays: true
    mouse_movement_humanization: true
    typing_delay_variation: true
  session_management:
    max_session_duration: 14400  # 4 heures en secondes
    break_duration_min: 1800  # 30 minutes
    break_duration_max: 3600  # 1 heure
    daily_limit: 43200  # 12 heures
    random_logout_chance: 0.02  # 2% de chance par action
  monitoring:
    screenshot_on_detection: true
    alert_webhook_url: ""  # URL webhook Discord/Slack
    email_alerts: false
    
# Configuration réseau et API
network:
  timeout: 30
  max_retries: 3
  retry_delay: 5
  user_agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36"
  proxy:
    enabled: false
    type: "http"  # http, https, socks4, socks5
    host: ""
    port: 0
    username: ""
    password: ""

# Configuration vision et OCR
vision:
  screenshot_method: "mss"  # mss, pillow, opencv
  template_matching:
    method: "cv2.TM_CCOEFF_NORMED"
    threshold: 0.8
    multiscale: true
    scale_factors: [0.8, 0.9, 1.0, 1.1, 1.2]
  ocr:
    engine: "tesseract"
    language: "fra"
    config: "--psm 6 -c tessedit_char_whitelist=0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz "
  preprocessing:
    gaussian_blur: true
    threshold: true
    erosion: false
    dilation: false

# Configuration combat
combat:
  ai_enabled: true
  auto_target: true
  spell_priority_system: true
  distance_optimization: true
  teamplay_coordination: true
  retreat_threshold: 30  # % de vie
  potion_usage:
    health_threshold: 50  # % de vie
    mana_threshold: 30  # % de mana
  spell_delays:
    min_delay: 200  # ms
    max_delay: 800  # ms
  targeting:
    priority_order: ["closest_enemy", "weakest_enemy", "strongest_enemy"]
    ignore_summons: false
    focus_fire: true

# Configuration navigation
navigation:
  pathfinding_algorithm: "astar"
  movement_speed: "normal"  # slow, normal, fast
  obstacle_avoidance: true
  dynamic_pathfinding: true
  zaap_usage: true
  recall_scroll_usage: false
  movement_delays:
    min_delay: 500
    max_delay: 1500
  areas:
    safe_zones: []
    forbidden_zones: []
    preferred_routes: {}

# Configuration professions
professions:
  enabled: ["farmer", "miner", "lumberjack", "alchemist"]
  auto_craft: true
  resource_optimization: true
  market_integration: true
  inventory_management: true
  experience_priority: false  # true pour XP, false pour kamas
  farming_routes:
    optimization_type: "efficiency"  # efficiency, safety, variety
    resource_respawn_time: 300  # secondes
  crafting:
    auto_buy_materials: false
    profit_margin_threshold: 0.15  # 15%
    max_investment: 100000  # kamas

# Configuration économie
economy:
  market_analysis: true
  auto_selling: false
  price_monitoring: true
  profit_tracking: true
  hdv_integration: true
  market_scan_interval: 1800  # 30 minutes
  selling_strategy:
    undercut_percentage: 0.01  # 1%
    minimum_profit_margin: 0.1  # 10%
    quick_sale_threshold: 0.05  # 5%
  inventory:
    auto_sort: true
    keep_quantity: 100  # quantité minimum à garder
    emergency_sell_threshold: 0.9  # 90% inventaire plein

# Configuration automation
automation:
  daily_routine: true
  quest_automation: true
  leveling_automation: true
  achievement_hunting: false
  dungeon_farming: false
  routine_schedule:
    start_time: "08:00"
    end_time: "22:00"
    break_frequency: 7200  # 2 heures
  objectives:
    primary: "leveling"  # leveling, farming, crafting, trading
    level_target: 200
    profession_targets:
      farmer: 100
      miner: 100
      lumberjack: 100

# Configuration modules
modules:
  core:
    enabled: true
    priority: 1
  combat:
    enabled: true
    priority: 2
  navigation:
    enabled: true
    priority: 3
  professions:
    enabled: true
    priority: 4
  economy:
    enabled: false
    priority: 5
  vision:
    enabled: true
    priority: 6
  safety:
    enabled: true
    priority: 7
  automation:
    enabled: true
    priority: 8
  social:
    enabled: false
    priority: 9

# Configuration personnage
character:
  class: ""  # À configurer par l'utilisateur
  name: ""   # À configurer par l'utilisateur
  level: 1
  server: ""
  breed_id: 0
  stats_priority: []  # Priorité des stats pour l'équipement
  spell_variants: {}  # Variantes de sorts préférées
  equipment_sets: []  # Sets d'équipement sauvegardés

# Configuration interface
interface:
  window_title: "Dofus"
  game_resolution: [1920, 1080]
  ui_scale: 1.0
  interface_elements:
    chat_box: [10, 850, 500, 200]
    inventory: [1600, 100, 300, 600]
    spell_bar: [600, 1000, 700, 80]
    minimap: [1700, 10, 200, 200]

# Configuration notifications
notifications:
  enabled: true
  types:
    level_up: true
    death: true
    full_inventory: true
    low_health: true
    disconnection: true
    achievement: true
  methods:
    desktop: true
    sound: false
    webhook: false
  webhook_url: ""

# Variables d'environnement (référence)
environment:
  # Ces variables doivent être définies dans .env
  # DOFUS_USERNAME=votre_nom_utilisateur
  # DOFUS_PASSWORD=votre_mot_de_passe
  # WEBHOOK_URL=votre_url_webhook
  # DATABASE_ENCRYPTION_KEY=votre_clé_de_chiffrement